### PR TITLE
Merge against latest google/gopacket master

### PR DESCRIPTION
**Pull request by cv**
There were mostly conflicts around imports, at least one block of CGo that needs a little more careful inspection, and a conflict in DecodeFromBytes which could use a glance, too.

This is required by https://github.com/elastic/beats/pull/4719.

### CODE REVIEW

**Comment by tsg** [comment]
That sounds less bad than I was afraid of. How do you propose we continue? Is there a way for me to review the conflicted files?

I'm thinking we could merge this one, and then try to update the vendored copy in Packetbeat, to see if anything broke. If it gets to messy, we can still revert the merge.

**Comment by cv** [comment]
Sounds good, @tsg! Unfortunately, I don't think there's an easy way to tell git to show only changes in conflicted files, as once they're merged that information is lost.

I think it's possible to point the vendored copy in Packetbeat at this branch in order to test it, so `master` on this repo isn't left at any point in time in a potentially broken state (don't know how much that would matter, tbh - up to you).

**Comment by tsg** [comment]
@cv Thanks! I'm going to do the merging next week because we're just before a feature freeze and don't want to take risks until we branch out the current release.

**Comment by cv** [comment]
Cleaning up my PR queue, feel free to take over this PR if it's still valuable!

**Pull request closed without merging**
